Merge changes to scripts from trunk

diff --git a/sarge/installer/doc/manual/scripts/create_po b/sarge/installer/doc/manual/scripts/create_po
--- a/sarge/installer/doc/manual/scripts/create_po
+++ b/sarge/installer/doc/manual/scripts/create_po
@@ -21,82 +21,57 @@ WORKDIR="./integrated"
 SOURCEDIR="$WORKDIR/$language"
 PODIR="./po"
 
-if [ -d "$PODIR" ] ; then
-    echo "Deleting old .po files for '$language'..."
-    for i in `find $PODIR/ -name "*.$language.po"` ; do
-        rm $i
-    done
+if [ ! -d "$PODIR" ] ; then
+    echo "Error: directory $PODIR does not exist."
+    exit 1
+fi
+
+mkdir -p $PODIR/$language
+if [ -n "$PODIR/$language/*.po" ] ; then
+    echo "Deleting old PO files for '$language'..."
+    rm $PODIR/$language/*.po
 fi
 
 XMLLIST=$(find $SOURCEDIR -name "*.xml")
 
-echo "Creating .po files for language '$language'..."
+echo "Creating PO files for language '$language'..."
+
+export NO_CREDITS=1      # Repress KDE specific credits
+                         # Note: not yet supported by split2po
+
 for SOURCEXML in $XMLLIST ; do
     SUBDIR=$(dirname $SOURCEXML | sed "s:$SOURCEDIR::" | sed "s:^/::")
-    if [ ! -d $PODIR/$SUBDIR ] ; then
-        echo "Skipping $SUBDIR; directory does not exist under $PODIR"
-        continue
-    fi
     XML=$(basename $SOURCEXML)
     ORIGXML=$WORKDIR/en/$SUBDIR/$XML
-    PO=$PODIR/$SUBDIR/$(basename $SOURCEXML .xml).$language.po
+    PO=$PODIR/$language/$(basename $SOURCEXML .xml).po
 
-    echo "Converting translated $SUBDIR/$XML to .po file"
+    echo "Converting translated $SUBDIR/$XML to PO file"
     split2po $ORIGXML $SOURCEXML >$PO
     if [ $? -ne 0 ] ; then
         echo "** Error during conversion."
         continue
     fi
-
-    # Remove strange references created by split2po
-    # Note: this is a workaround for a bug in the tools:
-    #       http://bugs.kde.org/show_bug.cgi?id=90112
-    if grep -q "POXML_" $PO ; then
-        echo "   Converting "POXML_" references..."
-        cat $PO | \
-            sed "s/!POXML_AMP!/\&/g" | \
-            sed "s/        /\\\t/g" | \
-            sed "s/&POXML_SPACE;/ /g" | \
-            sed "s/&POXML_LINEFEED;/\\\n\"\n      \"/g" | \
-            sed "s/&POXML_LT;/</g" | \
-            sed "s/&POXML_GT;/>/g" \
-            >/tmp/tmp.po.$$
-        cp /tmp/tmp.po.$$ $PO
-    fi
-    # Check if there are any we don't yet know about
-    if grep "POXML_" $PO ; then
-        echo "** Error: file contains unknown "POXML_" references."
-    fi
-
-    # Remove spurious msgid's created by split2po (drop last 6 lines)
-    # Note: this is a workaround for a feature in the tools:
-    #       http://bugs.kde.org/show_bug.cgi?id=90112
-    if grep "ROLES_OF_TRANSLATORS" $PO >/dev/null; then
-        LINES=$(cat $PO | wc -l)
-        head -n $(($LINES - 6)) $PO >/tmp/tmp.po.$$
-        cp /tmp/tmp.po.$$ $PO
-    fi
 done
 
 # Check the results
 echo ""
-echo "Checking whether translation matches corresponding .pot file..."
-for PO in `find $PODIR -name "*.$language.po"` ; do
-    TDIR=$(dirname $PO); POT=$(basename $PO ".$language.po").pot
+echo "Checking whether translation matches corresponding POT file..."
+for PO in `find $PODIR/$language -name "*.po"` ; do
+    POT="$PODIR/pot/$(basename $PO .po).pot"
     if [ -s $PO ] ; then
-        if [ -f $TDIR/$POT ] ; then
-            count_POT=$(egrep "^msgid " $TDIR/$POT | wc -l)
+        if [ -f $POT ] ; then
+            count_POT=$(egrep "^msgid " $POT | wc -l)
             count_PO=$(egrep "^msgstr " $PO | wc -l)
             if [ $count_PO != $count_POT ] ; then
                 echo "** Warning: translation for $PO has $count_PO strings, while original has $count_POT strings."
             fi
-            count_missing_PO=$(egrep "^msgstr \"\"$" $PO | wc -l)
-            count_missing_PO=$(($count_missing_PO - 1))
+            # Missing strings: If a line with 'msgstr ""' is followed by an empty line.
+            count_missing_PO=$(egrep -A 1 "^msgstr \"\"$" $PO | egrep "^$" | wc -l)
             if [ $count_missing_PO -ne 0 ] ; then
                 echo "** Warning: translation for $PO has $count_missing_PO missing strings."
             fi
         else
-            echo "** Error: corresponding .pot file not found for $PO."
+            echo "** Error: corresponding POT file not found for $PO."
         fi
     else
         echo "** Error: $PO is empty (conversion error)."
@@ -106,15 +81,15 @@ echo "Done."
 
 # Checking for untranslated strings
 echo ""
-echo "Checking for untranslated strings in the .po files..."
-for PO in `find po/ -name "*.$language.po"` ; do
+echo "Checking for untranslated strings in the PO files..."
+for PO in `find $PODIR/$language -name "*.po"` ; do
     echo "Checking $PO..."
     awk -f $SCRIPTDIR/mark_untranslated.awk $PO
 done
 
 echo ""
 echo "The conversion has finished successfully."
-echo "The .po files for $language have been saved in '$PODIR'."
+echo "The PO files for $language have been saved in '$PODIR/$language'."
 echo ""
 echo "Please check all messages above very carefully."
 echo "If any translations are shown to have a different amount of strings than the original,"
diff --git a/sarge/installer/doc/manual/scripts/create_xml b/sarge/installer/doc/manual/scripts/create_xml
--- a/sarge/installer/doc/manual/scripts/create_xml
+++ b/sarge/installer/doc/manual/scripts/create_xml
@@ -10,31 +10,48 @@ fi
 
 language=${1:-pl}
 
-WORKDIR="./integrated"
+BUILDDIR="./build"
+if [ -z "$PO_USEBUILD" ] ; then
+    WORKDIR="./integrated"
+    PODIR="./po"
+else
+    WORKDIR="$BUILDDIR/build.po"
+    PODIR="$BUILDDIR/build.po"
+fi
 SOURCEDIR="$WORKDIR/en"
-PODIR="./po"
-LANGDIR="./$language.new"
+# Don't overwrite XML translations committed to SVN
+if [ -d "./$language/.svn" ] ; then
+    TARGETDIR="./$language.new"
+else
+    TARGETDIR="./$language"
+fi
+RET=0
 
 [ -d "$SOURCE" -o -d "$PODIR" ] || exit 1
 
-[ -d "$LANGDIR" ] && rm $LANGDIR/*.xml
+[ -d "$TARGETDIR" ] && rm -r $TARGETDIR
 
-echo "Creating .xml files for language $language"
+echo "Creating XML files for language '$language':"
 for ORIGXML in `find $SOURCEDIR -name "*.xml"` ; do
-    SUBDIR=$(dirname $ORIGXML | sed "s:$SOURCEDIR::" | sed "s:^/::")
+    BASEDIR=$(dirname $ORIGXML | sed "s:$SOURCEDIR::" | sed "s:^/::")
     BASENAME=$(basename $ORIGXML .xml)
-    PO=$PODIR/$SUBDIR/$BASENAME.$language.po
-    XML=$LANGDIR/$SUBDIR/$BASENAME.xml
+    PO=$PODIR/$language/$BASENAME.po
+    XML=$TARGETDIR/$BASEDIR/$BASENAME.xml
 
-    mkdir -p $LANGDIR/$SUBDIR
+    mkdir -p $TARGETDIR/$BASEDIR
 
     if [ -f $PO ] ; then
-        echo "- $SUBDIR/$BASENAME: creating translated .xml"
+        echo "- creating $BASENAME.xml"
         po2xml $ORIGXML $PO > $XML
+        RC=$?
+        if [ $RC -ne 0 ] ; then
+            RET=$RC
+            echo "Error: error $RC while executing po2xml"
+        fi
     else
-        echo "* $SUBDIR/$BASENAME: no .po file found; copying English original"
-        cp $ORIGXML $LANGDIR/$SUBDIR
+        echo "Warning: no PO file found for '$BASENAME'; copying English original"
+        cp $ORIGXML $TARGETDIR/$BASEDIR
     fi
 done
 
-exit 0
+exit $RET
