Merge from trunk, revisions r60940 to r61063

diff --git a/kfreebsd/netboot-assistant/di-netboot-assistant b/kfreebsd/netboot-assistant/di-netboot-assistant
--- a/kfreebsd/netboot-assistant/di-netboot-assistant
+++ b/kfreebsd/netboot-assistant/di-netboot-assistant
@@ -65,9 +65,10 @@ DI-DIST
 	the file '$DISOURCELIST')
 
 Commands:
-    install - download and extract a netboot image.
-    uninstall - remove a previously installed netboot image.
-    purge - equivalent to uninstall plus uncache.
+    install      - download and extract a netboot image.
+    uninstall    - remove a previously installed netboot image.
+    uncache      - remove downloaded files from the cache.
+    purge        - equivalent to uninstall plus uncache.
     rebuild-menu - rebuild the top level menu.
 
 Options:
@@ -151,6 +152,7 @@ update_pxelinux_menu() {
 		echo "" >> pxelinux.cfg/default
 	done
 	[ $i -eq 0 ] && rm pxelinux.cfg/default
+	rm pxelinux.cfg/default.mig-bak 2>/dev/null || true
 
 	i=0
 	if [ -f "pxelinux.cfg/default.serial-9600" ]; then
@@ -258,10 +260,23 @@ uninstall_repos() {
 	[ "$DEBUG" ] && set -x
 	del_repo="$1"
 	ignore_missing="$2"
-	current_repos="$(find  "${STATUS_LIB}/"  -name $del_repo--\*.conf | sed -e 's/^.*--//' -e 's/\.conf//')"
+
+	if [ ! -d "${STATUS_LIB}" ]; then
+		echo "E: Failed to uninstall repository, lib folder not found." 1>&2
+		exit 1
+	fi
+
+	installed_archs="$(find  "${STATUS_LIB}/"  -name \*$del_repo--\*.conf | sed -e 's/^.*--//' -e 's/\.conf//')"
+	if [ ! "$installed_archs" -a "$ignore_missing" != "ignore_missing" ]; then
+		installed_repos="$(find  "${STATUS_LIB}/"  -name \*--\*.conf | sed -e 's,^.*/,,' -e 's/--.*\.conf//')"
+		echo "E: Repository '$del_repo' not ininstalled." 1>&2
+		echo "I: (installed repositories are: $installed_repos)" 1>&2
+		echo "" 1>&2
+		exit 1
+	fi
 
 	if [ "$(echo $ARCH | grep -E "\<all\>")" ]; then
-		archs="$current_repos"
+		archs="$installed_archs"
 	else
 		archs="$(echo $ARCH | tr ',' ' ')"
 	fi
@@ -272,7 +287,7 @@ uninstall_repos() {
 		else
 			if [ "$ignore_missing" != "ignore_missing" ]; then
 				echo "E: Repository '$del_repo' for architecture '$a' doesn't exists." 1>&2
-				echo "I: (current repository are: $current_repos)"
+				echo "I: (installed arch are: $installed_archs)"
 				echo "" 1>&2
 				exit 1
 			fi
@@ -315,21 +330,24 @@ remove_repocaches() {
 	local COUNT
 	[ "$DEBUG" ] && set -x
 	del_repo="$1"
+	ignore_missing="$2"
 
 	if [ ! -d "${DL_CACHE}" ]; then
 		echo "E: Failed to clean the cache, cache folder not found." 1>&2
 		exit 1
 	fi
 
-	current_repos="$(find ${DL_CACHE} -name "*~~$del_repo--*.meta" | sed -e 's/^.*--//' -e 's/\.meta//' | tr '\n' ' ')"
-	if [ ! "$current_repos" ]; then
+	cached_archs="$(find ${DL_CACHE} -name "*~~$del_repo--*.meta" | sed -e 's/^.*--//' -e 's/\.meta//' | tr '\n' ' ')"
+	if [ ! "$cached_archs" -a "$ignore_missing" != "ignore_missing" ]; then
+		cached_repos="$(find /home/fpiat/.di-netboot-assistant/cache -name \*~~\*--\*.meta | sed -e 's/^.*~~//' -e 's/--.*//' | tr '\n' ' ')"
 		echo "E: Repository '$del_repo' not cached." 1>&2
+		echo "I: (cached repositories are: $cached_repos)" 1>&2
 		echo "" 1>&2
-		exit 0
+		exit 1
 	fi
 
 	if [ "$(echo $ARCH | grep -E "\<all\>")" ]; then
-		archs="$current_repos"
+		archs="$cached_archs"
 	else
 		archs="$(echo $ARCH | tr ',' ' ')"
 	fi
@@ -341,9 +359,9 @@ remove_repocaches() {
 			COUNT=$(( $COUNT + 1 ))
 		done
 
-	        if [ $COUNT -eq 0 ]; then
+	        if [ $COUNT -eq 0 -a "$ignore_missing" != "ignore_missing" ]; then
 			echo "E: Repository '$del_repo' for architecture '$a' doesn't exists." 1>&2
-			echo "I: (current repository are: $current_repos)" 1>&2
+			echo "I: (cached archs are: $cached_archs)" 1>&2
 			echo "" 1>&2
 			exit 1
 		fi
@@ -565,17 +583,10 @@ install_repo() {
 		f=$(echo $givenfile | sed -e 's#^\./##' -e 's#^/##' -e 's#//#/#g')
 		dl_file="${DL_CACHE}/$(echo ${repo_loc}/$f | url2filename)"
 
-#FIXME
-		# get the metadata from the downloaded repository
+		# get existing metadata from the downloaded repository
 		cat "${DL_CACHE}/$(echo ${repo_loc}~~${release}--${arch}.meta | url2filename)" > $metadatafile
-
-#		echo "#$PACKAGE_NAME for '$release' ($arch)" > $metadatafile
-#		echo "fetch_date=$fetch_date" >> $metadatafile
-
 		echo "expand_dir=$expand_dir" >> $metadatafile
-#		echo "dist=$release" >> $metadatafile
-#		echo "repo=$repo" >> $metadatafile
-#		echo "dl_file=$dl_file" >> $metadatafile
+#FIXME: MAke those two lines to work !
 #		echo "di_args=$DI_ARGS" >> $metadatafile
 #		echo "target_args=$TARGET_ARGS" >> $metadatafile
 
@@ -630,7 +641,7 @@ install_repo() {
 			for x in $(find "$expand_dir" -type f -a \( -name "default" -o -name "boot.txt" -o -name '*.cfg' \) ); do
 				mv "$x" "$x.ORIG"
 				print_do-not-edit_header "$release netboot image" > "$x"
-				sed -e "s#${REWRITEPKGPATH}/$arch/#debian-installer/${REPO_ALIAS}/$arch/#" "$x.ORIG" \
+				sed -e "s#${REWRITEPKGPATH}/$arch/#::/debian-installer/${REPO_ALIAS}/$arch/#" "$x.ORIG" \
 					| tweak_pxelinux_arguments >> "$x"
 			done
 			menufragment="$metadatabasename.pxelinux.menu.fragment"
@@ -667,20 +678,18 @@ install_repo() {
 				echo   "	APPEND debian-installer/${REPO_ALIAS}/$arch/pxelinux.cfg/default" >> $menufragment
 			fi
 
-			echo   "" >> $menufragment
 
 			if [ -f "$menufragment_serial9600" ]; then
 				echo   "LABEL ${REPO_ALIAS}-$arch" >> $menufragment_serial9600
 				printf "	MENU LABEL Debian Installer %-20s       [SUB-MENU]\n" "(${REPO_ALIAS}, $arch)" >> $menufragment_serial9600
-				echo   "	KERNEL debian-installer/pxelinux.cfg/$SYSLINUXMENU" >> $menufragment_serial9600
-				echo   "	APPEND debian-installer/${REPO_ALIAS}/$arch/pxelinux.cfg.serial-9600/default" >> $menufragment_serial9600
-				echo   "" >> $menufragment_serial9600
+				echo   "	KERNEL ::/debian-installer/pxelinux.cfg/$SYSLINUXMENU" >> $menufragment_serial9600
+				echo   "	APPEND ::/debian-installer/${REPO_ALIAS}/$arch/pxelinux.cfg.serial-9600/default" >> $menufragment_serial9600
 			fi
 		fi
 
-		# ELILO MENU (ia64)
+		# ELILO MENU (ia64, and some ia32)
 		if [ ! -z "$(find "$expand_dir" -type f -name 'elilo.conf' )" ]; then
-+			#Rewrite existing menus
+			#Rewrite existing menus
 			for x in $(find "$expand_dir" -type f -name 'elilo.conf' ); do
 				mv "$x" "$x.ORIG"
 				print_do-not-edit_header "release" > "$x"
@@ -863,7 +872,7 @@ for option in "$@"; do
 			;;
 		purge)
 			uninstall_repos "$option" ignore_missing 
-			remove_repocaches "$option"
+			remove_repocaches "$option" ignore_missing
 			;;
 		rebuild-menu)
 			echo "W: Argument '$option' ignored ($ACTION expects no argument)." 1>&2
